#include "test_common.h"

int failed_tests = 0;

void test_vm_memory_initialization();
void test_vm_endianness();
void test_vm_get_memory_size();
void test_vm_addi();
void test_vm_zr_hardwiring();
void test_vm_oob();
void test_vm_alu();
void test_vm_lpcr();
void test_vm_ac();
void test_vm_l64();
void test_vm_l32();
void test_vm_l32s();
void test_vm_l16();
void test_vm_l16s();
void test_vm_l8();
void test_vm_l8s();
void test_vm_lf64();
void test_vm_s64();
void test_vm_s32();
void test_vm_s16();
void test_vm_s8();
void test_vm_sf64();
void test_vm_jal();
void test_vm_jalr();
void test_vm_beq();
void test_vm_bne();
void test_vm_blt();
void test_vm_bge();
void test_vm_sblt();
void test_vm_sbge();
void test_vm_slt();
void test_vm_sslt();
void test_vm_and();
void test_vm_or();
void test_vm_xor();
void test_vm_andi();
void test_vm_ori();
void test_vm_xori();
void test_vm_sll();
void test_vm_srl();
void test_vm_sra();
void test_vm_slli();
void test_vm_srli();
void test_vm_srai();
void test_vm_imf64();
void test_vm_f64mi();
void test_vm_icf64();
void test_vm_f64ci();
void test_vm_fpu();
void test_vm_fsi64();
void test_vm_fsin64();
void test_vm_fsix64();
void test_vm_fmin64();
void test_vm_fmax64();
void test_vm_feq64();
void test_vm_flt64();
void test_vm_fle64();
void test_vm_fclass64();

int main()
{
  test_vm_memory_initialization();
  test_vm_endianness();
  test_vm_get_memory_size();
  test_vm_addi();
  test_vm_zr_hardwiring();
  test_vm_oob();
  test_vm_alu();
  test_vm_lpcr();
  test_vm_ac();
  test_vm_l64();
  test_vm_l32();
  test_vm_l32s();
  test_vm_l16();
  test_vm_l16s();
  test_vm_l8();
  test_vm_l8s();
  test_vm_lf64();
  test_vm_s64();
  test_vm_s32();
  test_vm_s16();
  test_vm_s8();
  test_vm_sf64();
  test_vm_jal();
  test_vm_jalr();
  test_vm_beq();
  test_vm_bne();
  test_vm_blt();
  test_vm_bge();
  test_vm_sblt();
  test_vm_sbge();
  test_vm_slt();
  test_vm_sslt();
  test_vm_and();
  test_vm_or();
  test_vm_xor();
  test_vm_andi();
  test_vm_ori();
  test_vm_xori();
  test_vm_sll();
  test_vm_srl();
  test_vm_sra();
  test_vm_slli();
  test_vm_srli();
  test_vm_srai();
  test_vm_imf64();
  test_vm_f64mi();
  test_vm_icf64();
  test_vm_f64ci();
  test_vm_fpu();
  test_vm_fsi64();
  test_vm_fsin64();
  test_vm_fsix64();
  test_vm_fmin64();
  test_vm_fmax64();
  test_vm_feq64();
  test_vm_flt64();
  test_vm_fle64();
  test_vm_fclass64();
  if (failed_tests > 0)
  {
    return 1;
  }
  return 0;
}
